-- AlterTable
ALTER TABLE "Minion" ADD COLUMN "strength" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Minion" ADD COLUMN "agility" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Minion" ADD COLUMN "intelligence" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Minion" ADD COLUMN "endurance" INTEGER NOT NULL DEFAULT 10;
