-- 장비 품질·아이템 레벨
ALTER TABLE "WeaponInstance" ADD COLUMN IF NOT EXISTS "quality" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "WeaponInstance" ADD COLUMN IF NOT EXISTS "qualityCraftCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "WeaponInstance" ADD COLUMN IF NOT EXISTS "itemLevel" INTEGER NOT NULL DEFAULT 10;

ALTER TABLE "ArmorInstance" ADD COLUMN IF NOT EXISTS "quality" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ArmorInstance" ADD COLUMN IF NOT EXISTS "qualityCraftCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ArmorInstance" ADD COLUMN IF NOT EXISTS "itemLevel" INTEGER NOT NULL DEFAULT 10;
